In [1]:
import warnings
warnings.filterwarnings('ignore')

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity ='all'

import numpy as np
import pandas as pd

# Question 1

In [14]:
def arrays(arr):
    li = list(map(float,arr))
    li.reverse()
    array = np.array(li)
    return(array)



In [15]:
arr = input().strip().split()
arrays(arr)


1 2 3 4 -8 -10


array([-10.,  -8.,   4.,   3.,   2.,   1.])

In [20]:
arr = input().strip().split()

array = np.array(list(map(float,arr)))
print(array)
rev_arr = array[::-1]
print(rev_arr)

1 2 3 4 -8 -10
[  1.   2.   3.   4.  -8. -10.]
[-10.  -8.   4.   3.   2.   1.]


# Question 2

In [21]:
n = list(map(int,input().strip().split()))
arr = np.array(n)
arr1 = arr.reshape(3,3)
print(arr1)

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


# Question 3

In [33]:
n,m = map(int,input().split())
arr =  [input().split() for i in range(n)]
arr = np.array(arr,dtype = 'int')
arr
print(arr)

2 2
1 2
3 4


array([[1, 2],
       [3, 4]])

[[1 2]
 [3 4]]


In [34]:
arr.dtype

dtype('int32')

In [35]:
print("Flatten array is:",arr.flatten(),sep = '\n')
print("Transposed array is:",arr.transpose(),sep = '\n')

Flatten array is:
[1 2 3 4]
Transposed array is:
[[1 3]
 [2 4]]


# Question 4

In [42]:
n,m,p = map(int,input().split())
l1 = []
for i in range(n):
    arr = input().split()
    l1.append(arr)
arr1 = np.array(l1,dtype = 'int')
l2 = [input().split() for i in range(m)]
arr2 = np.array(l2,dtype = 'int')
concate = np.concatenate((arr1,arr2),axis=0)
print(concate)

4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


# Question 5

In [16]:
num = list(map(int,input().strip().split()))
print(np.zeros(num,dtype = np.int))
print(np.ones(num,dtype = np.int))

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


# Question 6

In [44]:
n,m = map(int,input().strip().split())


3 3
3 3


In [48]:
print(np.identity(n))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [49]:
print(np.eye(n,m,))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Question 7

In [65]:
n,m = map(int,input().strip().split())
arr1 = [input().split() for i in range(n)]
A = np.array(arr1,dtype = np.int)
arr2 = [input().split() for i in range(n)]
B = np.array(arr2,dtype = np.int)

print('sum of elements in A&B is :' , np.add(A,B))
print('subtractioni of elements in A&B is :', np.subtract(A,B))
print('multiplication of elements in  A&B is :' ,np.multiply(A,B))
print('integer division of elemnts in  A&B is :' ,np.floor_divide(A,B))
print(' remainder of elemnts of in  A&B is :' ,np.mod(A,B))
print('power of A&B is :' ,np.power(A,B))






1 4
1 2 3 4
5 6 7 8
sum of elements in A&B is : [[ 6  8 10 12]]
subtractioni of elements in A&B is : [[-4 -4 -4 -4]]
multiplication of elements in  A&B is : [[ 5 12 21 32]]
integer division of elemnts in  A&B is : [[0 0 0 0]]
 remainder of elemnts of in  A&B is : [[1 2 3 4]]
power of A&B is : [[    1    64  2187 65536]]


# Question 8

In [17]:
A = list(map(float,input().split()))
A = np.array(A)
print(np.floor(A))
print(np.ceil(A))
print(np.rint(A))

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[1. 2. 3. 4. 5. 6. 7. 8. 9.]
[ 2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 1.  2.  3.  4.  6.  7.  8.  9. 10.]


# Question 9

In [23]:
n,m = map(int,input().strip().split())
arr = [input().split()for i in range(n)]
array = np.array(arr,dtype= np.int)
sum_ax_0 = np.sum(array,axis=0)
print(np.prod(sum_ax_0))

2 2
1 2
3 4
24


# Question 10

In [26]:
n,m = map(int,input().strip().split())
arr = [input().strip().split() for i in range(n)]
array = np.array(arr,dtype=np.int)
min_ax_1 = np.min(array,axis=1)
print(np.max(min_ax_1))

4 2
2 5
3 7
1 3
4 0
3


# Question 11

In [28]:
n,m = map(int,input().strip().split())
arr = [input().strip().split() for i in range(n)]
array = np.array(arr,dtype = np.int)
print(np.mean(array,axis= 1))
print(np.var(array,axis=0))
print(np.std(array))

2 2
1 2
3 4
[1.5 3.5]
[1. 1.]
1.118033988749895


In [29]:
print(round(np.std(array),ndigits=11))


1.11803398875


# Question 12

Dot and cross product

You are given two arrays A and B . Both have dimensions of NXN.
Your task is to compute their matrix product.

Input Format

The first line contains the integer N.
The next N lines contains N space separated integers of array A.
The following N lines contains N space separated integers of array b.

Output Format

Print the matrix multiplication of A and B.


In [17]:
n = int(input())
arr1 = [input().split() for i in range(n)]
A    = np.array(arr1,dtype=np.int)
arr2 = [input().split() for i in range(n)]
B    = np.array(arr2,dtype= np.int)
print(np.dot(A,B))

2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]
[0 0]


# Question 13

In [26]:
n = int(input())
arr = [input().strip().split() for i in range(n)]
A = np.array(arr,dtype=np.float)
determinant = round(np.linalg.det(A),2)
print(determinant)


2
1.1 1.1
1.1 1.2
0.11


# Question 14

In [32]:
p = input().strip().split()
x= int(input())
poly = np.array(p,dtype = np.float)
print (np.polyval(poly,x))  

1.1 2 3
0
3.0


# Question 15

In [33]:
n = input().strip().split()
m = input().strip().split()
A = np.array(n,dtype= np.int)
B = np.array(m,dtype= np.int)

print(np.inner(A,B))
print(np.outer(A,B))

0 1
2 3
3
[[0 0]
 [2 3]]
